domainNameBase: hurst.stratusgriddev.com
hostname: stra
restApiLoggingRole: arn:aws:iam::973081273628:role/sg-dev-api-gw-logging-us-east-1

# In dev, even critical alarms go to noncritical alarms
# This lets them be used for rollback testing, letting devs know about issues, etc. but won't wake anyone up
snsCriticalAlarmArn: arn:aws:sns:us-east-1:973081273628:sg-dev-test-serverless-noncritical-alarms-us-east-1
snsCriticalOkArn: arn:aws:sns:us-east-1:973081273628:sg-dev-test-serverless-noncritical-alarms-us-east-1
snsNonCriticalAlarmArn: arn:aws:sns:us-east-1:973081273628:sg-dev-test-serverless-noncritical-alarms-us-east-1